import type { Metadata } from "next";
import "./globals.css";

import { Inter } from 'next/font/google';

// 'Inter' 폰트 설정
const inter = Inter({
  subsets: ['latin'],  // 사용할 문자 집합
  variable: '--font-inter',  // CSS 변수로 설정
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}`}
      >
        {children}
      </body>
    </html>
  );
}
