import type { Metadata } from "next";
import "./globals.css";

import { Inter, Montserrat } from 'next/font/google';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter'
});

const montserrat = Montserrat({ 
  subsets: ['latin'],
  weight: ['700']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${montserrat.className}`}
      >
        {children}
      </body>
    </html>
  );
}
